### ISSUE TITLE
Missing ability to apply multiple validations on single input

### ISSUE THREAD

**Issue by vukasin-nikodijevic** [ScottMGerstl/ng2-validate#7]
With jQuery validator plugin I was able to apply multiple Validations on single input which is super useful.

Example: [EmailValidation, MaxValidation]

Is this possible here and if yes how.

Currently I must create custom validation class which will reflect exact combination of validation rules I need.
This way code is hard to maintain as it can grow up to infinity.

**Comment by ScottMGerstl** [comment]
Good MV\* design would suggest having the view yield the responsibility of orchestrating the validation to show. 

In the example where you want to always apply email and max validations could pose a couple problems for you: 

1) if both validations are violated, both messages will show, if this is not what you want, since this library has the control bound to the message list it would be impossible to selectively display messages using the validation messages component. 

2) if you always want to show all validation - consider the example: [Required, Email, Min]. If nothing is in the input, all three messages will show; this is likely frustrating for the user as most users only want as much information as they need when they need it. 

These things said, I have not actively programmed out the ability to do as you have asked after. Instead of:

```
let emailControl: Control = new Control('', new EmailValidation().validator);
```

It would be: 

```
let emailControl: Control = new Control('', [Required, Email, Min]);
```

Keep in mind, the validation you add to the array must follow the ValidatorFn interface defined by angular. You can explore their repo to learn more. Since this library also follows the interface, the components will still work.

I would like to mention the benefit of creating validation as it is documented. If you want to use the same field logic over again, having the validation logic encapsulated in a validator allows you to reuse the logic without a lot of copy and paste.

**Comment by vukasin-nikodijevic** [comment]
Thanks this is what I needed - I'll play with this later tonight ;)

Cheers

**Comment by ScottMGerstl** [comment]
How did it go? Did you find what your were looking for?

**Comment by vukasin-nikodijevic** [comment]
Still busy with project. Probably tomorrow I'll have some tome to dedicate.
